buildpacks:
  blobstore_type: local
  local_config:
    path_prefix: /tmp/buildpacks
droplets:
  blobstore_type: local
  local_config:
    path_prefix: /tmp/droplets
packages:
  blobstore_type: local
  local_config:
    path_prefix: /tmp/packages

app_stash:
logging:
  file: /tmp/bits-service.log
  syslog: vcap.bits-service
  level: debug
public_endpoint: public.127.0.0.1.xip.io
private_endpoint: internal.127.0.0.1.xip.io
secret: geheim
port: 8000
