resources:
- name: git-bits-service
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bits-service.git
    branch: master
    path: ci/docker/Dockerfile
- name: flintstone-ci-image
  type: docker-image
  source:
    repository: flintstonecf/ci
    email: {{dockerhub-email}}
    username: {{dockerhub-username}}
    password: {{dockerhub-password}}

jobs:
  - name: create-image
    plan:
    - get: git-bits-service
      trigger: true
    - put: flintstone-ci-image
      params: { build: git-bits-service/ci/docker }
