groups:
- name: bits-service
  jobs:
  - run-tests
- name: bits-service-release
  jobs:
  - build-deploy-and-test
- name: cf-release
  jobs:
  - deploy-cf-release
  - CATs

resources:
- name: git-bits-service
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bits-service.git
    branch: master
- name: git-bits-service-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/bits-service-release.git
    branch: master
- name: git-cf-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release.git
    branch: master
    submodules: none
    depth: 1
- name: bits-service-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: bits-service
- name: cf-deployment
  type: bosh-deployment
  source:
    target: {{bosh-target}}
    username: {{bosh-username}}
    password: {{bosh-password}}
    deployment: cf-warden
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
- name: cf-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

jobs:
- name: run-tests
  plan:
  - get: git-bits-service
    trigger: true
  - task: run-tests
    file: git-bits-service/ci/tasks/run-tests.yml
- name: build-deploy-and-test
  plan:
  - aggregate:
    - get: git-bits-service-release
      trigger: true
    - get: stemcell
  - task: create-release-and-manifest
    file: git-bits-service-release/ci/tasks/create-release-and-manifest.yml
    config:
      params:
        BOSH_TARGET: {{bosh-target}}
        BOSH_USERNAME: {{bosh-username}}
        BOSH_PASSWORD: {{bosh-password}}
  - put: bits-service-deployment
    params:
      cleanup: true
      manifest: assets/manifest.yml
      stemcells:
      - stemcell/stemcell.tgz
      releases:
      - assets/bits-service-*.tgz
  - task: test
    config:
      inputs:
      - name: git-bits-service-release
      image: docker:///tutum/curl
      run:
        path: git-bits-service-release/test/test.sh
- name: deploy-cf-release
  plan:
  - aggregate:
    - get: stemcell
    - get: cf-release
    - get: git-cf-release
      params:
        submodules: none
        depth: 1
    - get: git-bits-service-release
      trigger: true
      passed:
        - build-deploy-and-test
    - get: stemcell
  - task: generate-cf-manifest
    config:
      platform: linux
      image: docker:///concourse/concourse-ci
      inputs:
        - name: git-bits-service-release
        - name: git-cf-release
      outputs:
        - name: assets
      run:
        path: git-bits-service-release/ci/scripts/generate-cf-manifest.sh
      params:
        BOSH_TARGET: {{bosh-target}}
        BOSH_USERNAME: {{bosh-username}}
        BOSH_PASSWORD: {{bosh-password}}
  - put: cf-deployment
    params:
      manifest: assets/manifest.yml
      stemcells:
      - stemcell/stemcell.tgz
      releases:
      - cf-release/release.tgz

- name: CATs
  plan:
  - get: git-bits-service-release
    trigger: true
    passed:
        - deploy-cf-release
  - task: run-cats
    config:
      platform: linux
      image: docker:///concourse/concourse-ci
      inputs:
        - name: git-bits-service-release
      run:
        path: git-bits-service-release/ci/scripts/run-errand.sh
      params:
        BOSH_TARGET: {{bosh-target}}
        BOSH_USERNAME: {{bosh-username}}
        BOSH_PASSWORD: {{bosh-password}}
        ERRAND_NAME: acceptance_tests
